create table base_model
(dtype varchar(31) not null,
id bigint not null,
create integer,
deleter integer,
gmt_create datetime,
gmt_delete datetime,
gmt_modified datetime,
gmt_update datetime,
modifier integer,
uuid varchar(255),
age integer,
gender bit,
identity_id varchar(255),
 mobile varchar(255),
 name varchar(255),
 native_place varchar(255),
 password varchar(255),
 salt varchar(255),
 username varchar(255),
 primary key (id))
